apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sbhello
  name: sbhello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbhello
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sbhello
    spec:
      containers:
      - image: sb-hello:1.0
        name: sb-hello
        resources: {}
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sbhello
  name: sbhello
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sbhello
  type: ClusterIP
status:
  loadBalancer: {}
